name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:
    
jobs:
  format-check-lib:
    uses: ./.github/workflows/format.yml

  lint-lib:
    uses: ./.github/workflows/lint.yml

  unit-test:
    uses: ./.github/workflows/test.yml

  integration-test:
    uses: ./.github/workflows/integration-test.yml
